# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enputi < Formula
  desc "A self-developing tool"
  homepage "https://github.com/darabuchi/enputi"
  version "0.0.6"
  license "Mozilla"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/darabuchi/enputi/releases/download/v0.0.6/enputi_v0.0.6_darwin_amd64.tar.gz"
    sha256 "61750ffa79eebee3996b9c957bdb7daad19361c9f2d914917f30e977ddc87958"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/darabuchi/enputi/releases/download/v0.0.6/enputi_v0.0.6_darwin_arm64.tar.gz"
    sha256 "bbf1ccb5971086c492857a2e14433515b2cb0f9f9b146b01f80c2b392e1d1e00"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/darabuchi/enputi/releases/download/v0.0.6/enputi_v0.0.6_linux_amd64.tar.gz"
    sha256 "de6ec2b07502a9e1a76b2be482bf4e185a765373cf237c3129335e0f06a39afe"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/darabuchi/enputi/releases/download/v0.0.6/enputi_v0.0.6_linux_arm64.tar.gz"
    sha256 "56ee127c33ed22a014c8d4283fb08c0aa9a4ca1ede2e3f753dc585a39335d042"
  end

  def install
    bin.install "enputi"
  end
end
